- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ['~', '~/.config']

- link:
    ~/.vimrc: vimrc
    ~/.bashrc: bashrc
    ~/.gitignore_global: gitignore_global
    ~/.vimrc: vimrc
    ~/.zprofile: zprofile
    ~/.zshrc: zshrc
    ~/.Brewfile: Brewfile
    ~/.aliases: aliases
    ~/.gitalias.txt: gitalias/gitalias.txt
    ~/.gitconfig: gitconfig
    ~/.tmux.conf: myalacritty/tmux.conf
    ~/.config/alacritty/alacritty.yml: myalacritty/alacritty.yml

- shell:
  # Install brew
  -
    command: source check_brew_install.sh
    stdin: true
    stout: true
    stderr: true
    # Link dotbot
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git submodule update
  # Install brew dependencies
  - brew bundle --no-lock --global
  - brew update & brew install cmake python go nodejs vim llvm
  # Install pyenv and python versions with its dependencies
  - source install-pyenv-and-pythons
  # Add GitAlias
  - git config --global include.path ~/.gitalias.txt
  # Clone vim/Vundle
  - git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim 2> /dev/null || (cd ~/.vim/bundle/Vundle.vim ; git pull)
  - git clone https://github.com/ycm-core/YouCompleteMe ~/.vim/bundle/YouCompleteMe 2> /dev/null || (cd ~/.vim/bundle/YouCompleteMe ; git pull)
  # Install vim plug-ins
  - vim +PluginInstall +qall
  - python3 ~/.vim/bundle/YouCompleteMe/install.py --all --clang-completer --system-libclang
  - vim +CocInstall coc-json coc-tsserver coc-json coc-html coc-css coc-python coc-go +qall
